default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
exclude: |
  (?x)(
      ^.codeocean/|
      ^environment/|
      ^metadata/|
      ^code/MOSuite|
      ^code/SCWorkflow|
      ^code/OMIX*
   )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10240"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
  # spell check
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args:
          [ -I, .github/WORDLIST.txt ]
  # R formatting
  - repo: https://github.com/posit-dev/air-pre-commit
    rev: 0.10.0
    hooks:
      - id: air-format
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9028
    hooks:
      - id: parsable-R
  # Python formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.16
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  # enforce conventional commit format
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
